### ISSUE TITLE
How to write a simple RequestController generating HTML?

### ISSUE THREAD

**Issue by jkleiser** [stablekernel/aqueduct#131]
I have tried again and again, but this far I have not been able to write a RequestController that generates a simple HTML page. Why is there no tiny example showing the proper way to do that in the tutorials?

**Comment by joeconwaystk** [comment]
In 1.0.3, the following works:

```
void setupRouter(Router router) {
    Response.addEncoder(new ContentType("text", "html"), (v) => v.toString());
    router
        .route("/page")
        .listen((req) async {
          return new Response.ok("<html>hello</html>", headers: {"Content-Type": "text/html"});
        });
}
```

Because Content-Type here is case-sensitive and not easily documented, and because all text/* content type encoders should be available by default, 1.0.4 will have some changes based on your feedback. It adds a contentType property to a Response and makes all responses with text/* contentType encodable. Then, you'd only need:

```
void setupRouter(Router router) {
    router
        .route("/page")
        .listen((req) async {
          return new Response.ok("<html>hello</html>")
              ..contentType = ContentType.HTML;
        });
}
```

**Comment by jkleiser** [comment]
For some reason, your 1.0.3 example does not work for me. Chrome says status 500, and in my api.log I see this:
```
[INFO] 2016-11-21 07:53:26.902083 aqueduct: Server aqueduct/1 started.
[INFO] 2016-11-21 07:53:27.301007 aqueduct: Server aqueduct/2 started.
[INFO] 2016-11-21 07:53:27.696732 aqueduct: Server aqueduct/3 started.
[SEVERE] 2016-11-21 07:53:43.157396 aqueduct: 127.0.0.1 GET /page 10ms 500 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36\nconnection : keep-alive\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\naccept-language : en-GB,en-US;q=0.8,en;q=0.6\naccept-encoding : gzip, deflate, sdch, br\nhost : localhost:8000\nupgrade-insecure-requests : 1\n} -  Instance of 'RequestException' #0      Request._encodeBody (package:aqueduct/http/request.dart:173:7)\n#1      Request.respond (package:aqueduct/http/request.dart:150:7)\n#2      RequestController.receive.<receive_async_body> (package:aqueduct/http/request_controller.dart:152:13)\n#3      _RootZone.runUnary (dart:async/zone.dart:1404)\n#4      _FutureListener.handleValue (dart:async/future_impl.dart:131)\n#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)\n#6      _Future._propagateToListeners (dart:async/future_impl.dart:667)\n#7      _Future._complete (dart:async/future_impl.dart:467)\n#8      _SyncCompleter.complete (dart:async/future_impl.dart:52)\n#9      RequestController.processRequest.<processRequest_async_body> (package:aqueduct/http/request_controller.dart:171:7)\n#10     _RootZone.runUnary (dart:async/zone.dart:1404)\n#11     _FutureListener.handleValue (dart:async/future_impl.dart:131)\n#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)\n#13     _Future._propagateToListeners (dart:async/future_impl.dart:667)\n#14     _Future._complete (dart:async/future_impl.dart:467)\n#15     _SyncCompleter.complete (dart:async/future_impl.dart:52)\n#16     AqueTestSink.setupRouter.<anonymous closure>.<<anonymous closure>_async_body> (package:aque_test/src/aque_test_sink.dart:59:5)\n#17     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)\n#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)\n#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)\n
```

**Comment by joeconwaystk** [comment]
👍
