### ISSUE TITLE
aqueduct 3.0 create & serve error on windows

### ISSUE THREAD

**Issue by MrParano1d** [stablekernel/aqueduct#429]
OS: Windows 10 Pro 64-Bit-Version

What I tried:

I installed dart 2 and aqueduct 3.0 like guided in your prerelease doc.
When I create a project with "aqueduct create project_name" I get my project folder but when I try "pub get" I recieve following error:

```
Exists failed, path = '/E:/Development/dart/aqueduct/aqueduct/' (OS Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
, errno = 123)
```

I found following config in the cli created pubspec.yaml

```
dependency_overrides:
  aqueduct:
    path:  /E:/Development/dart/aqueduct/aqueduct/
  aqueduct_test:
    path:  /E:/Development/dart/aqueduct/aqueduct_test/
```

It seems like you're putting a slash in front of every path. After I removed them I could execute "pub get" without any errors.

But when I tried "aqueduct serve" I recieve following error:

```
E:\Development\dart\projects\dart_megalodon>aqueduct serve
-- Aqueduct CLI Version: 3.0.0
-- Aqueduct project version: 3.0.0
-- Preparing...
*** Uncaught error
    FileSystemException: Cannot open file, path = '/E:/Development/dart/aqueduct/aqueduct/lib/src/commands/scripts/get_channel_type.dart' (OS Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.
, errno = 123)
  **** Stacktrace
  * #0      _File.throwIfError (dart:io/file_impl.dart:628)
  * #1      _File.openSync (dart:io/file_impl.dart:472)
  * #2      _File.readAsBytesSync (dart:io/file_impl.dart:532)
  * #3      _File.readAsStringSync (dart:io/file_impl.dart:577)
  * #4      parseDartFile (package:analyzer/analyzer.dart:57:36)
  * #5      SourceGenerator._getClass (package:isolate_executor/src/source_generator.dart:55:22)
  * <asynchronous suspension>
  * #6      SourceGenerator.scriptSource (package:isolate_executor/src/source_generator.dart:21:31)
  * <asynchronous suspension>
  * #7      IsolateExecutor.execute (package:isolate_executor/src/executor.dart:56:38)
  * <asynchronous suspension>
  * #8      IsolateExecutor.executeWithType (package:isolate_executor/src/executor.dart:95:21)
  * <asynchronous suspension>
  * #9      CLIServer.deriveApplicationLibraryDetails (package:aqueduct/src/commands/serve.dart:178:40)
  * <asynchronous suspension>
  * #10     CLIServer.prepare (package:aqueduct/src/commands/serve.dart:196:32)
  * <asynchronous suspension>
  * #11     CLIServer.handle (package:aqueduct/src/commands/serve.dart:86:11)
  * <asynchronous suspension>
  * #12     CLICommand.process (package:aqueduct/src/commands/base.dart:146:20)
  * <asynchronous suspension>
  * #13     CLICommand.process (package:aqueduct/src/commands/base.dart:122:48)
  * <asynchronous suspension>
  * #14     main (file:///E:/Development/dart/aqueduct/aqueduct/bin/aqueduct.dart:9:27)
  * <asynchronous suspension>
  * #15     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
  * #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
  ****
```

Again there's a slash in front the path and I don't find any configs to remove it. 

Do you have a solution for this issue? I really would like to start my test project with the newest version of dart & aqueduct.

Thanks in advance.

**Comment by joeconwaystk** [comment]
Thanks for filing the issue. Windows is a weakness right now; we don't have CI that runs on Windows or even a Windows machine in our office. On that note, do you have any recommendations for a CI tool for Windows that have you experience with?

The workaround is to run the application via `bin/main.dart` script. 

However, this error is coming from a dependency (that we own) that will impact all CLI tools. Do you mind if I change this issue title to 'Run CI on Windows platform'?

**Comment by MrParano1d** [comment]
I'm pretty new to dart myself so I don't know any other CI tool. Sorry.

I don't mind if you rename this issue.

Running it with the main.dart works. Thank you. :)
