### ISSUE TITLE
Form body is blank when using `isProduction: true`

### ISSUE THREAD

**Issue by seenickcode** [stablekernel/aqueduct#611]
Has anyone ever had an issue where you POST a form but none of the form body fields are able to be read?

```@Operation.post()
  Future<Response> createUser() async {
    final data = {
      "passwordRequirementsMessage": "Minimum $passwordMinLength characters."
    };
    final form = html.formBody(request);
    logger.log(Level.INFO, 'signing up with form: ${form.toString()}');
    final user = User()..readFromMap(form);
    if (user.email.isEmpty || user.password.isEmpty) {
      return html.renderBadRequest(
          request,
          html.loadTemplate(subdir: "register"),
          ["Email and password required."],
          data: data);
    }
```

My form:

```<h1>Sign Up</h1>

<form action="/register" method="post">
  <div class="table form">
    <div class="row">
      <div class="cell field">
        <label for="fname">First name:</label>
        <input type="text" id="fname" name="fname" width=20 autofocus />
      </div>
      <div class="cell field">
        <label for="lname">Last name:</label>
        <input type="text" id="lname" name="lname" width=20 />
      </div>
    </div>
    <div class="row">
      <div class="cell field">
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" width=20 />
        <p><small>Required. After registering, you'll be required to verify this email.</small></p>
      </div>
    </div>
```

Stack trace:
```[INFO] aqueduct: signing up with form: {}  
[SEVERE] aqueduct: POST /register 18ms 500 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36\nx-forward-for : 173.76.53.80\nconnection : upgrade\ncache-control : max-age=0\nx-real-ip : 173.76.53.80\naccept-encoding : gzip, deflate, br\ndnt : 1\ncontent-type : application/x-www-form-urlencoded\nx-forwarded-proto : https\nreferer : https://fluttercrashcourse.com/register\nsave-data : on\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\naccept-language : en-US,en;q=0.9,es;q=0.8,ru;q=0.7,de;q=0.6\ncookie : _ga=GA1.2.1989785999.1543340645; _gid=GA1.2.1304399406.1546091927; _gat_gtag_UA_122935010_1=1; mp_831c108f9cb2220b0e431bbb7f9749 ... (306 truncated bytes)\norigin : https://fluttercrashcourse.com\ncontent-length : 78\nhost : fluttercrashcourse.com\nupgrade-insecure-requests : 1\n}  NoSuchMethodError: The getter 'isEmpty' was called on null.
Receiver: null
Tried calling: isEmpty #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      RegisterController.createUser (package:fcc/controllers/register_controller.dart:47:20)
<asynchronous suspension>
#2      _LocalInstanceMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:327:37)
#3      _LocalInstanceMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:323:25)
#4      BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:23:10)
#5      ResourceController._process (package:aqueduct/src/http/resource_controller.dart:394:36)
<asynchronous suspension>
#6      ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:137:14)
<asynchronous suspension>
#7      Controller.receive (package:aqueduct/src/http/controller.dart:173:30)
<asynchronous suspension>
#8      _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:401:17)
#9      Controller.receive (package:aqueduct/src/http/controller.dart:205:28)
<asynchronous suspension>
#10     Router.receive (package:aqueduct/src/http/router.dart:139:18)
<asynchronous suspension>
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#15     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#20     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#21     _StreamController._add (dart:async/stream_controller.dart:639:7)
#22     _StreamController.add (dart:async/stream_controller.dart:585:5)
#23     _HttpServer._handleRequest (dart:_http/http_impl.dart:2665:19)
```

<img width="1443" alt="screen shot 2018-12-29 at 5 27 01 pm" src="https://user-images.githubusercontent.com/75833/50542698-d6989c80-0b91-11e9-865d-f09766cd52a6.png">

On my localhost, this works fine, but in production, I’m getting a 500  error because this `final form = html.formBody(request);` becomes an empty map

I’m using Aqueduct `3.0.2`

**Comment by seenickcode** [comment]
It appears that I'm running this behind nginx reverse proxy and it's stripping out all the form POST param values. Still an issue but I'll have to I guess research this myself.

**Comment by thosakwe** [comment]
Set `proxy_pass_request_body` to `on`, and you should be fine: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass_request_body

**Comment by seenickcode** [comment]
Yeah I was thinking the same thing, but the docs said it's "on" by default.
I added it anyway and removed some of the settings I had copied over from
older code (that had been used for web sockets). After simplifying my
config I'm back on track. Thanks Tobe.
