### ISSUE TITLE
type 'List<Serializable>' is not a subtype of type 'List<Filial>' of 'list'

### ISSUE THREAD

**Issue by siloebb** [stablekernel/aqueduct#641]
When I'm trying to  `post` a `List` of a `ManagedObject` I receive this 

> type 'List<Serializable>' is not a subtype of type 'List<Filial>' of 'list'

When I try to use just a single object instead a List it works.

My classes are just simple:
```
class Filial extends ManagedObject<_Filial> implements _Filial{}
class _Filial {
  @primaryKey
  int codfilial;
  String nome;
  String image;
  String cnpj;
  String email;
  @Column(defaultValue: 'true')
  bool ativo;

  ManagedSet<ProductFilial> productFilial;
}
```

**My Post controller:**

```
@Operation.post()
  Future<Response> createFilial(@Bind.body() List<Filial> list) async {
    return Response.ok('No Errors');
  }
```

**My Log:**

```
type 'List<Serializable>' is not a subtype of type 'List<Filial>' of 'list' #0      _TypeError._throwNew (dart:core/runtime/liberrors_patch.dart:89:51)
#1      _LocalInstanceMirror._invoke (dart:mirrors/runtime/libmirrors_impl.dart:327:37)
#2      _LocalInstanceMirror.invoke (dart:mirrors/runtime/libmirrors_impl.dart:323:25)
#3      BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:23:10)
#4      ResourceController._process (package:aqueduct/src/http/resource_controller.dart:397:36)
<asynchronous suspension>
#5      ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:138:14)
<asynchronous suspension>
#6      Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
<asynchronous suspension>
#7      _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:402:17)
#8      Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#9      Router.receive (package:aqueduct/src/http/router.dart:139:18)
<asynchronous suspension>
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#14     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     _HttpServer._handleRequest (dart:_http/http_impl.dart:2656:19)
#23     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2414:19)
#24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#27     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#28     _StreamController._add (dart:async/stream_controller.dart:640:7)
#29     _StreamController.add (dart:async/stream_controller.dart:586:5)
#30     _HttpParser._headersEnd (dart:_http/http_parser.dart:386:17)
#31     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#32     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#33     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#38     _StreamController._add (dart:async/stream_controller.dart:640:7)
#39     _StreamController.add (dart:async/stream_controller.dart:586:5)
#40     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#41     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#44     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#45     _StreamController._add (dart:async/stream_controller.dart:640:7)
#46     _StreamController.add (dart:async/stream_controller.dart:586:5)
#47     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#48     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#49     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#51     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

I googled a lot but I saw that is relative to SDK, I'm Using:
**aqueduct: ^3.1.0+1
sdk: 2.2.0-1**

**Comment by joeconwaystk** [comment]
There was a breaking change in Dart 2.1.1 (and >2.2.0). It has been remedied in the Aqueduct master branch and will get pushed to pub in Aqueduct 3.2 release this week.

**Comment by joeconwaystk** [comment]
This is now deployed to pub v3.2.0
