### ISSUE TITLE
Document broke when use a List

### ISSUE THREAD

**Issue by siloebb** [stablekernel/aqueduct#652]
I receive this error when I try to create the document of the API, I just use `aqueduct document`.
I can use normally the endpoint, and the test are ok.

The error happens when I have a Post with List as Parameter, like this:

```
Future<Response> createFilial({@Bind.body() List<Filial> list}) async {
...
}
```

This is what I receive:
```
*** Uncaught error
    Bad state: type 'List<Filial>' is not a subtype of type 'Serializable' in type cast
  **** Stacktrace
  * #0      ResourceController.documentComponents.<anonymous closure>.<anonymous closure> (package:aqueduct/src/http/resource_controller.dart:310:61)
  * #1      Iterable.forEach (dart:core/iterable.dart:277:30)
  * #2      ResourceController.documentComponents.<anonymous closure> (package:aqueduct/src/http/resource_controller.dart:305:12)
  * #3      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
  * #4      ResourceController.documentComponents (package:aqueduct/src/http/resource_controller.dart:300:13)
  * #5      _ControllerRecycler.documentComponents (package:aqueduct/src/http/controller.dart:419:29)
  * #6      Controller.documentComponents (package:aqueduct/src/http/controller.dart:299:23)
  * #7      Controller.documentComponents (package:aqueduct/src/http/controller.dart:299:23)
  * #8      Router.documentComponents.<anonymous closure> (package:aqueduct/src/http/router.dart:158:18)
  * #9      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
  * #10     Router.documentComponents (package:aqueduct/src/http/router.dart:157:23)
  * #11     ApplicationChannel.documentComponents (package:aqueduct/src/application/channel.dart:183:16)
  * #12     ApplicationChannel.documentAPI (package:aqueduct/src/application/channel.dart:167:5)
  * <asynchronous suspension>
  * #13     Application.document (package:aqueduct/src/application/application.dart:167:38)
  * <asynchronous suspension>
  * #14     OpenAPIBuilder.execute (<data:application/dart>:16:1572)
  * <asynchronous suspension>
  * #15     main (<data:application/dart>:12:35)
  * <asynchronous suspension>
  * #16     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:296:32)
  * #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
  ****
```

**Comment by joeconwaystk** [comment]
Thanks for finding this. This sounds like the addition to allowing binding of List<Serializable> was not accounted for when generating OpenAPI docs. 

Unfortunately, this requires a bug fix in the framework and the only workaround is not to use OpenAPI generation or to not bind List<Serializable>s (and instead read them directly from the request body). The fix is likely minor.

**Comment by joeconwaystk** [comment]
Fixed on master

**Comment by joeconwaystk** [comment]
3.2.1 release is now available on pub.
