### ISSUE TITLE
Error on fetch ID primary key column

### ISSUE THREAD

**Issue by junioregis** [stablekernel/aqueduct#744]
I need fetch ID column in my query **:(**

Exception on: **..returningProperties((e) => [e.id])**

```
@Table(name: "table")
class Table {
  @Column(primaryKey: true)
  int id;

  ...
}

class Entity extends ManagedObject<Table> implements Table {
  ...
}
        
class Controller extends ResourceController {
  Controller(this.context);

  final ManagedContext context;

  Future do() {
    final query = Query<Entity>(context)
      ..returningProperties((e) => [e.id])
      ..sortBy((item) => item.id, QuerySortOrder.descending);

    await query.fetchOne();

    ...
  }

  ...
}
```

**Exception:**

```
Unhandled exception:
NoSuchMethodError: The method 'any' was called on null.
Receiver: null
Tried calling: any(Closure: (KeyPath) => bool)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      QueryMixin.returningProperties (package:aqueduct/src/db/query/mixin.dart:109:20)
```

**QueryMixin:**

```
@override
void returningProperties(List<dynamic> propertyIdentifiers(InstanceType x)) {
  final properties = entity.identifyProperties(propertyIdentifiers);

=======> if (properties.any((kp) => kp.path.any((p) =>
    p is ManagedRelationshipDescription &&
    p.relationshipType != ManagedRelationshipType.belongsTo))) {
    throw ArgumentError(
        "Invalid property selector. Cannot select has-many or has-one relationship properties. Use join instead.");
  }

  _propertiesToFetch = entity.identifyProperties(propertyIdentifiers);
}
```

**Comment by joeconwaystk** [comment]
I tried replicating this and could not. I had to change the names of `Table` and `Controller` since those are existing classes; in reconfiguring this code to replicate it, this error did not occur. Can you provide the actual managed object, table and controller code you are using?

**Comment by junioregis** [comment]
Thank you for the prompt reply and, sorry, I'm late!

When I use a parent class to represent my entities, the error occurs.

I resolved by removing this parent class and working with the entities directly.

Below is the complete example:

@Table (name: "table1")
class Table 1 {
   @Column (primaryKey: true)
   int id;
}

@Table (name: "table2")
class Table2 {
   @Column (primaryKey: true)
   int id;
}

abstract class BaseEntity <T> extends ManagedObject <T> {
   int id;
}

class Entity1 extends BaseEntity <Table1> implements Table1 {
   ...
}

class Entity2 extends BaseEntity <Table2> implements Table2 {
   ...
}
        
class Controller extends ResourceController {
   Controller (this.context);

   final ManagedContext context;

   Future of () async {
     final query = Query <Entity1> (context)
       ..returningProperties ((e) => [e.id])
       ..sortBy ((item) => item.id, QuerySortOrder.descending);

     await query.fetchOne ();

     ...
   }

   ...
}

**Comment by joeconwaystk** [comment]
Got it - you can't create a class hierarchy with ManagedObjects. You can create a class hierarchy with table definitions (your plain Dart classes that have @Column annotations).

**Comment by junioregis** [comment]
Thanks! :)
