### ISSUE TITLE
Error on Request in dart 2.8.0-dev

### ISSUE THREAD

**Issue by Jailson66** [stablekernel/aqueduct#798]
The following error is occurring when making a request
Dart VM version: 2.8.0-dev.17.0.flutter-1402e8e1a4 (be) (Thu Mar 26 13:15:18 2020 +0000) on "windows_x64"

Note: in the stable version it is working correctly

My request
`router.route('api/test').linkFunction((request) async {

      final List<Category> list = await Query<Category>(context).fetch();
      return Response.ok(list);
    });`

Response:
`[INFO] aqueduct: PostgreSQL connecting, postgres@localhost:5432/myProject.
[SEVERE] aqueduct: GET /api/test 473ms 500 {user-agent : Mozilla/5.0 (Windows NT
 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Sa
fari/537.36 Edg/80.0.361. ... (2 truncated bytes)\nconnection : keep-alive\ncach
e-control : max-age=0\naccept : text/html,application/xhtml+xml,application/xml;
q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\nac
cept-language : pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\naccept-encoding
 : gzip, deflate\nhost : 192.168.0.121:8888\nupgrade-insecure-requests : 1\n}  R
angeError: Invalid value: Not in range 0..1114111, inclusive: -1 #0      StringB
uffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
#1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29
)
#2      Query.sendExtended (package:postgres/src/query.dart:61:38)
#3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connec
tion_fsm.dart:182:9)
#4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fs
m.dart:168:14)
#5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connecti
on.dart:399:67)
#6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.
dart:318:12)
#7      PostgreSQLPersistentStore.executeQuery (package:aqueduct/src/db/postgres
ql/postgresql_persistent_store.dart:297:38)
<asynchronous suspension>
#8      PostgresQuery._fetch (package:aqueduct/src/db/postgresql/postgresql_quer
y.dart:186:10)
#9      PostgresQuery.fetch (package:aqueduct/src/db/postgresql/postgresql_query
.dart:142:12)
#10     FaveReadsChannel._routerPrivate.<anonymous closure> (package:fave_reads/
channel.dart:43:60)
#11     _FunctionController.handle (package:aqueduct/src/http/controller.dart:43
8:20)
#12     Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
#13     Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#14     Router.receive (package:aqueduct/src/http/router.dart:139:18)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1337:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:
11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#19     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:1
66:13)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1337:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:
11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.da
rt:779:19)
#25     _StreamController._add (dart:async/stream_controller.dart:655:7)
#26     _StreamController.add (dart:async/stream_controller.dart:597:5)
#27     _HttpServer._handleRequest (dart:_http/http_impl.dart:2833:19)
#28     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2592:
19)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1337:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:
11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.da
rt:779:19)
#33     _StreamController._add (dart:async/stream_controller.dart:655:7)
#34     _StreamController.add (dart:async/stream_controller.dart:597:5)
#35     _HttpParser._headersEnd (dart:_http/http_parser.dart:385:19)
#36     _HttpParser._doParse (dart:_http/http_parser.dart:725:15)
#37     _HttpParser._parse (dart:_http/http_parser.dart:327:7)
#38     _HttpParser._onData (dart:_http/http_parser.dart:836:5)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1337:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:
11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.da
rt:779:19)
#43     _StreamController._add (dart:async/stream_controller.dart:655:7)
#44     _StreamController.add (dart:async/stream_controller.dart:597:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1967:41)
#46     _RootZone.runUnaryGuarded (dart:async/zone.dart:1337:10)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:
11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.da
rt:779:19)
#50     _StreamController._add (dart:async/stream_controller.dart:655:7)
#51     _StreamController.add (dart:async/stream_controller.dart:597:5)
#52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1512
:33)
#53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017
:14)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:
13)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:169:5)`

**Comment by Jailson66** [comment]
Found the problem and sent a postgresql correction request (substituter.dart line 101)
