### ISSUE TITLE
Authentication not working : dataModel was called on null

### ISSUE THREAD

**Issue by pratibhashali** [stablekernel/aqueduct#845]
Hi, I am trying to follow this tutorial:

https://aqueduct.io/docs/tut/oauth2/#setting-up-oauth-20-registering-users

I have added client and trying to authenticate the user by this piece of code:
`
```
import 'dart:convert';
import 'package:http/http.dart' as http;

void main(List<String> arguments) async {
  const clientID = 'com.myapp';
  const body = 'username=bob&password=bobby&grant_type=password';

// Note the trailing colon (:) after the clientID.
// A client identifier secret would follow this, but there is no secret, so it is the empty string.
  final clientCredentials =
      const Base64Encoder().convert('$clientID:'.codeUnits);

  final response = await http.post('http://localhost:8888/auth/token',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': 'Basic $clientCredentials'
      },
      body: body);
  print(response.body);
}
```
`

On the server side I get this error

```
[SEVERE] aqueduct: POST /auth/token 43ms 500 {user-agent : Dart/2.7 (dart:io)\ncontent-type : application/x-www-form-urlencoded; charset=utf-8\naccept-encoding : gzip\ncontent-length : 47\nhost : localhost:8888\nauthorization : Basic Y29tLm5pZGhpOg==\n}  NoSuchMethodError: The getter 'dataModel' was called on null.
Receiver: null
Tried calling: dataModel #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new Query (package:aqueduct/src/db/query/query.dart:30:28)      
#2      ManagedAuthDelegate.getClient (package:aqueduct/managed_auth.dart:426:19)
#3      AuthServer.getClient (package:aqueduct/src/auth/authorization_server.dart:127:21)
#4      AuthServer.authenticate (package:aqueduct/src/auth/authorization_server.dart:168:26)
#5      AuthController.grant (package:aqueduct/src/auth/auth_controller.dart:79:40)
#6      _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:327:37)
#7      _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:323:25)
#8      BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:24:10)
#9      ResourceController._process (package:aqueduct/src/http/resource_controller.dart:371:36)
<asynchronous suspension>
#10     ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:138:14)
<asynchronous suspension>
#11     Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
#12     _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:402:17)
#13     Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#14     Router.receive (package:aqueduct/src/http/router.dart:139:18)   
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#19     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)     
#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#25     _StreamController._add (dart:async/stream_controller.dart:642:7)#26     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#27     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)  
#28     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#33     _StreamController._add (dart:async/stream_controller.dart:642:7)#34     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#35     _HttpParser._headersEnd (dart:_http/http_parser.dart:388:17)    
#36     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)       
#37     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#38     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#43     _StreamController._add (dart:async/stream_controller.dart:642:7)#44     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)       
#46     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#50     _StreamController._add (dart:async/stream_controller.dart:642:7)#51     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)       
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)   
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
dart --version
Dart VM version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64"
```

```
aqueduct --version
Aqueduct CLI version: 3.3.0+1
```

UPDATE:
If I do not pass Authorization in header of request then it works fine and response is

```
{
    "error": "invalid_client"
}
```

Thanks 

Regards,
Sumit Sharma

**Comment by pratibhashali** [comment]
Got the answer to problem. 
It is strange
If I run 

`aqueduct serve `

then it starting two processes for me as I have quad-core PC  because of the below line in bin/main.dart.

```

final count = Platform.numberOfProcessors ~/ 2;
await app.start(numberOfInstances: count > 0 ? count : 1);
```


and each server was creating a different hash and salt they are randomly generated
```

aqueduct serve
-- Aqueduct CLI Version: 3.3.0+1
-- Aqueduct project version: 3.3.0+1
-- Preparing...
    Channel: NidhiServerChannel
    Config: E:\Flutter\nidhi-profile\config.yaml
    Port: 8888
com.nidhi 6blpfbS633Z3f9CbOd1MtfXODDG+jRv96wM9jHOd5jo= ne6XPTDxv9QaY6bjfSYVJ3155C6KBRFH2gFR7ziO1pE=
[INFO] aqueduct: Server aqueduct/1 started.
com.nidhi Z5mM6Czf8NNvoMUEwnwqFIQH2kEpMKvNntpufNU+kuA= kixQb9Xnw4nGH1PeVBJc5uL4v2Wdt4Dnt4bFbLGmMJg=
[INFO] aqueduct: Server aqueduct/2 started.
```

But if I ran

aqueduct serve -n1

then Authentication works fine and getting back
`
{"access_token":"UKbK14axcfnxiabI0tDCrlnWdHDVkOEr","token_type":"bearer","expires_in":86399,"refresh_token":"tEeMVVweD6LCnCrhiyZKFoOT5rxHxS7N"}`
 

Closing the issue for now but can anyone please let me know what was the problem when two servers were running?

**Comment by Reductions** [comment]
@pratibhashali 
There should not be a difference whether you run the multi-isolate or not.

Can you explain what was the hash that was generated differently?

**Comment by Reductions** [comment]
Can you post your channel source code?

**Comment by pratibhashali** [comment]
Code to print clientid and hashedSecret

```
var credentials =
        AuthUtility.generateAPICredentialPair("com.nidhi", "myparispecial");
    print("${credentials.id} ${credentials.hashedSecret} ${credentials.salt}");
```


Output when running on multiple isolates
Server 1

> Client Id: com.nidhi 
> hashedSecret: 6blpfbS633Z3f9CbOd1MtfXODDG+jRv96wM9jHOd5jo= 
> salt : ne6XPTDxv9QaY6bjfSYVJ3155C6KBRFH2gFR7ziO1pE=
> [INFO] aqueduct: Server aqueduct/1 started.


Server 2


> Client Id: com.nidhi 
> hashedSecret: Z5mM6Czf8NNvoMUEwnwqFIQH2kEpMKvNntpufNU+kuA= 
> salt : kixQb9Xnw4nGH1PeVBJc5uL4v2Wdt4Dnt4bFbLGmMJg= 
> [INFO] aqueduct: Server aqueduct/2 started.

You can see the difference between 
credentials.hashedSecret and credentials.salt

**Comment by pratibhashali** [comment]
@Reductions 

This is the code of channel.dart

```
class MyAppChannel extends ApplicationChannel {
  AuthServer authServer;
  ManagedContext context;
  //ManagedAuthDelegate<User> delegate;

  @override
  Future prepare() async {
    var credentials =
        AuthUtility.generateAPICredentialPair("com.nidhi", "myparispecial");
    print("${credentials.id} ${credentials.hashedSecret} ${credentials.salt}");

    //* Setting up auth server OAuth2.0
    final delegate = ManagedAuthDelegate<User>(context);
    logger.onRecord.listen(
        (rec) => print("$rec ${rec.error ?? ""} ${rec.stackTrace ?? ""}"));

    final config = ApplicationConfiguration("config.yaml");

    final dataModel = ManagedDataModel.fromCurrentMirrorSystem();
    final persistentModel = PostgreSQLPersistentStore.fromConnectionInfo(
      config.userDatabase.username,
      config.userDatabase.password,
      config.userDatabase.host,
      config.userDatabase.port,
      config.userDatabase.databaseName,
    );

    context = ManagedContext(dataModel, persistentModel);
    final authStorage = ManagedAuthDelegate<User>(context);
    //authServer = AuthServer(delegate);
    authServer = AuthServer(authStorage);
  }

  @override
  Controller get entryPoint {
    final router = Router();

    //* Adding authorization routes in the application
    //* This grants and refreshes tokens
    router.route("/auth/token").link(() => AuthController(authServer));

    //* Set up auth code route - this grants temporary access code that can be exchanged for token
    //router.route("auth/code").link(() => AuthCodeController(authServer));

    // Prefer to use `link` instead of `linkFunction`.
    // See: https://aqueduct.io/docs/http/request_controller/
    router
        .route("/profile/[:id]")
        .link(() => ProfileController(context: context));

    router
        .route("/protectedprofile/[:id]")
        .link(() => Authorizer.bearer(authServer))
        .link(() => ProfileController(context: context));

    router.route("/hello").linkFunction((request) =>
        Response.ok('Hello World')..contentType = ContentType.json);

    router.route('/client').linkFunction((request) async {
      final client = await File('client.html').readAsString();
      return Response.ok(client)..contentType = ContentType.html;
    });

    router
        .route("/register")
        .link(() => RegisterController(context, authServer));

    return router;
  }
}
```

**Comment by Reductions** [comment]
Ok first you probably should not use a client with a  secret.
Second you should not generate client every time you start you application it should be create once and reused. Actually your code doesn't use the client generate by `AuthUtility.generateAPICredentialPair` as it is never inserted into the database.

**Comment by Reductions** [comment]
Ok the problem is this. The following code is called before the context is initialized:

```dart
    final delegate = ManagedAuthDelegate<User>(context);
```

That is why you have such an error `Receiver: null` as in context is `null`.

**Comment by pratibhashali** [comment]
> AuthUtility.generateAPICredentialPair

1. This was just for testing purpose

2. This is not being used if look closely

> final delegate = ManagedAuthDelegate<User>(context);

**Comment by Reductions** [comment]
Usually you will issue a client with secret when another service would use your app. For example a 3th partty app or another internal service. As I guess you will use the aqueduct for a backend of a front end application you don't need to have a secret as it will not be a secret at all.
