### ISSUE TITLE
aqueduct document crashes

### ISSUE THREAD

**Issue by poznanski** [stablekernel/aqueduct#867]
aqueduct crashes when trying to generate OpenAPI client web page

> aqueduct document client
-- Aqueduct CLI Version: 4.0.0-b1
-- Aqueduct project version: 4.0.0-b1
*** Uncaught error
    Bad state: NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<String, dynamic>(Closure: (dynamic, dynamic) => MapEntry<String, dynamic>)
  **** Stacktrace
  * #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
  * #1      new Configuration.fromString (package:safe_config/src/configuration.dart:23:17)
  * #2      new Configuration.fromFile (package:safe_config/src/configuration.dart:30:44)
  * #3      new BumpConfig (package:parkio_bump_server/channel.dart:37:34)
  * #4      ParkioBumpServerChannel.prepare (package:parkio_bump_server/channel.dart:12:20)
  * #5      Application.document (package:aqueduct/src/application/application.dart:165:26)
  * <asynchronous suspension>
  * #6      OpenAPIBuilder.execute (<data:application/dart>:17:1821)
  * #7      main (<data:application/dart>:13:35)
  * #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
  * #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****
>

**Comment by owczaro** [comment]
@poznanski, after upgrading dart to the newest version I had similar problem, but during `aqueduct db generate`. Try to add `pub run ` before all aqueduct commands. It's temporary solution, but works though

**Comment by poznanski** [comment]
after downgrading aqueduct version I got a meaningful error message about my classes, unfortunately I did not saved it. Anyway, I guess it is a problem of error reporting. If maintainers want, they can close the issue. Thanks.
