### ISSUE TITLE
aqueduct build Error 

### ISSUE THREAD

**Issue by DiegoLimeiradaSilva** [stablekernel/aqueduct#868]
when trying to deploy with aqueduct build

`-- Aqueduct CLI Version: 4.0.0-b1
-- Aqueduct project version: 4.0.0-b1
Resolving ASTs...
Generating runtime...
*** Uncaught error
    Bad state: Invalid argument(s): Cannot resolve relative URIs in file located at package:server/channel.dart. Replace imported URIs with package or absolute URIs 
  **** Stacktrace
  * #0      BuildContext.getImportDirectives.<anonymous closure> (package:runtime/src/build_context.dart:163:9)
  * #2      new List.from (dart:core-patch/array_patch.dart:47:19)
  * #3      Iterable.toList (dart:core/iterable.dart:400:12)
  * #4      BuildContext.getImportDirectives (package:runtime/src/build_context.dart:169:8)
  * #5      ConfigurationRuntimeImpl.compile (package:safe_config/src/runtime.dart:130:28)
  * #6      Build.execute.<anonymous closure> (package:runtime/src/build.dart:31:45)
  * #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
  * #8      Build.execute (package:runtime/src/build.dart:28:34)
  * <asynchronous suspension>
  * #9      BuildExecutable.execute (<data:application/dart>:13:259)
  * #10     main (<data:application/dart>:9:35)
  * #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
  * #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****
PS C:\Parceria\fnts\FixTocServer\server> aqueduct build
-- Aqueduct CLI Version: 4.0.0-b1
-- Aqueduct project version: 4.0.0-b1
Resolving ASTs...
Generating runtime...
*** Uncaught error
    Bad state: Invalid argument(s): Cannot resolve relative URIs in file located at package:server/channel.dart. Replace imported URIs with package or absolute URIs 
  **** Stacktrace
  * #0      BuildContext.getImportDirectives.<anonymous closure> (package:runtime/src/build_context.dart:163:9)
  * #1      MappedIterator.moveNext (dart:_internal/iterable.dart:395:20)
  * #2      new List.from (dart:core-patch/array_patch.dart:47:19)
  * #3      Iterable.toList (dart:core/iterable.dart:400:12)
  * #4      BuildContext.getImportDirectives (package:runtime/src/build_context.dart:169:8)
  * #5      ConfigurationRuntimeImpl.compile (package:safe_config/src/runtime.dart:130:28)
  * #6      Build.execute.<anonymous closure> (package:runtime/src/build.dart:31:45)
  * #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
  * #8      Build.execute (package:runtime/src/build.dart:28:34)
  * <asynchronous suspension>
  * #9      BuildExecutable.execute (<data:application/dart>:13:259)
  * #10     main (<data:application/dart>:9:35)
  * #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
  * #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

**Comment by Reductions** [comment]
Here lies the answer:
```
Bad state: Invalid argument(s): Cannot resolve relative URIs in file located at package:server/channel.dart. Replace imported URIs with package or absolute URIs
```
