### ISSUE TITLE
RangeError: Invalid value: Not in range 0..1114111, inclusive: -1

### ISSUE THREAD

**Issue by luX0r-reload** [stablekernel/aqueduct#869]
Hi. I'm experiment with PersistentStore and executeQuery method.
Just try a simple query:
```
final pStore = PostgreSQLPersistentStore('postgres', 'pal8375ad', 'localhost', 5432, 'MyTown');
const query = 'SELECT id, testo, attivo FROM lux_appo';
final rsets = await pStore.executeQuery(query, {}, const Duration(seconds: 30).inSeconds);
```
And I received Exception "RangeError: Invalid value: Not in range 0..1114111, inclusive: -1".

I'm running: psql (PostgreSQL) 12.3 and Dart VM version: 2.8.4 (stable).

This is the entire log:

```
[SEVERE] aqueduct: GET /appo 53ms 500 {user-agent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0\nconnection : keep-alive\ncache-control : max-age=0\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\naccept-language : it\naccept-encoding : gzip, deflate\ndnt : 1\nhost : localhost:8888\nupgrade-insecure-requests : 1\n}  RangeError: Invalid value: Not in range 0..1114111, inclusive: -1 #0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:76:9)
#1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
#2      Query.sendExtended (package:postgres/src/query.dart:61:38)
#3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
#4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
#5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
#6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
#7      PostgreSQLPersistentStore.executeQuery (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:297:38)
<asynchronous suspension>
#8      AppoController.getAppo (package:lux_aqueduct_server/controllers/appo_controller.dart:16:32)
#9      _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:339:37)
#10     _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:335:25)
#11     BoundOperation.invoke (package:aqueduct/src/http/resource_controller_internal/controller.dart:24:10)
#12     ResourceController._process (package:aqueduct/src/http/resource_controller.dart:371:36)
<asynchronous suspension>
#13     ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:138:14)
<asynchronous suspension>
#14     Controller.receive (package:aqueduct/src/http/controller.dart:174:30)
#15     _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:402:17)
#16     Controller.receive (package:aqueduct/src/http/controller.dart:206:28)
<asynchronous suspension>
#17     Router.receive (package:aqueduct/src/http/router.dart:139:18)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#21     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#22     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#28     _StreamController._add (dart:async/stream_controller.dart:655:7)
#29     _StreamController.add (dart:async/stream_controller.dart:597:5)
#30     _HttpServer._handleRequest (dart:_http/http_impl.dart:2837:19)
#31     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2596:19)
#32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#36     _StreamController._add (dart:async/stream_controller.dart:655:7)
#37     _StreamController.add (dart:async/stream_controller.dart:597:5)
#38     _HttpParser._headersEnd (dart:_http/http_parser.dart:399:19)
#39     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#40     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#41     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#42     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#52     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#53     _StreamController._add (dart:async/stream_controller.dart:655:7)
#54     _StreamController.add (dart:async/stream_controller.dart:597:5)
#55     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#56     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by luX0r-reload** [comment]
Ok. I used a dependency_overrides in pubspec.yaml to forcing use postgres: 2.1.1 as a temporary workaround, and it works.
Any news on a final fix?

Many thanks.

Luca

**Comment by mejiad** [comment]
I'm following the aqueduct tutorial and I get the same error after running the aqueduct db upgrade. I changed to postgres to 2.1.1 and I get the same error.

**Comment by luX0r-reload** [comment]
Yes, in db migration appears the same error and override postgres to 2.1.1 in pubspec.yaml does not solve it.

**Comment by mejiad** [comment]
> Yes, in db migration appears the same error and override postgres to 2.1.1 in pubspec.yaml does not solve it.
> 
> EDIT: Solved. Run `pub run aqueduct db upgrade` in application folder.

Thank you, that solved my problem.

**Comment by zmtzawqlp** [comment]
➜  server git:(master) ✗ aqueduct db upgrade

-- Aqueduct CLI Version: 3.3.0+1
-- Aqueduct project version: 3.3.0+1
*** Uncaught error
    RangeError: Invalid value: Not in inclusive range 0..1114111: -1
  **** Stacktrace
  * #0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:74:9)
  * #1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29)
  * #2      Query.sendExtended (package:postgres/src/query.dart:61:38)
  * #3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
  * #4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
  * #5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
  * #6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
  * #7      PostgreSQLPersistentStore.execute (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:153:37)
  * <asynchronous suspension>
  * #8      PostgreSQLPersistentStore.schemaVersion (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:216:26)
  * #9      CLIDatabaseUpgrade.handle (package:aqueduct/src/cli/commands/db_upgrade.dart:28:52)
  * #10     CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #11     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #12     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #13     main (file:///Users/roott/.pub-cache/hosted/pub.flutter-io.cn/aqueduct-3.3.0+1/bin/aqueduct.dart:9:27)
  * #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by zmtzawqlp** [comment]
The problem is  that + postgres 1.0.2 (2.2.0 available) is not the latest one, when i run   pub global activate aqueduct.

~  pub global activate aqueduct
Package aqueduct is currently active at version 3.3.0+1.
Resolving dependencies... (1.5s)
+ analyzer 0.35.4 (0.40.2 available)
+ aqueduct 3.3.0+1
+ args 1.6.0
+ async 2.4.2
+ charcode 1.1.3
+ codable 1.0.0
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ front_end 0.1.14 (0.1.29 available)
+ glob 1.2.0
+ isolate_executor 2.0.2+3
+ js 0.6.2
+ kernel 0.3.14 (0.3.29 available)
+ logging 0.11.4
+ meta 1.2.3
+ node_interop 1.1.1
+ node_io 1.1.1
+ open_api 2.0.1
+ package_config 1.9.3
+ password_hash 2.0.0
+ path 1.7.0
+ pedantic 1.9.2
+ postgres 1.0.2 (2.2.0 available)
+ pub_cache 0.2.3
+ pub_semver 1.4.4
+ safe_config 2.0.2
+ source_span 1.7.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ watcher 0.9.7+15
+ yaml 2.2.1
Precompiling executables... (14.6s)
Precompiled aqueduct:aqueduct.
Installed executable aqueduct.
Activated aqueduct 3.3.0+1.

we can clone aqueduct to local and activate it from local.

pub global activate --source path ./

and add dependencies from local.

dependencies:
  aqueduct:
    path: /Users/xxxx/xxxx/xxxx/aqueduct/aqueduct

**Comment by RGkevin** [comment]
It was getting this error by running `$ aqueduct db upgrade` (dart from flutter).

How I fixed it
override dependency to postgre
pubspec.yaml
dependency_overrides:
  postgres: 2.1.1

then run this using pub
`$ flutter pub run aqueduct db upgrade`
