### ISSUE TITLE
Converting object to an encodable object failed

### ISSUE THREAD

**Issue by aloenobilis** [stablekernel/aqueduct#892]
Hi,

running ```brew install dart``` fetches dart 2.9.2 on channel-beta.
and dart 2.8.4 on channel-master.

This seems to be incompatible with -- Aqueduct CLI Version: 4.0.0-b1 -- Aqueduct project version: 4.0.0-b1

What version of dart works with aqueduct 4.0.0-b1? 2.8.4 or 2.9.2? 

Getting an error:
[part of heroes tut]
```
[SEVERE] aqueduct: GET /heroes 56ms 500 {user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4251.0 Safari/537.36\nconnection : keep-alive\naccept : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b ... (7 truncated bytes)\naccept-language : en-US,en;q=0.9\nsec-fetch-dest : document\nsec-fetch-mode : navigate\naccept-encoding : gzip, deflate, br\nhost : localhost:8888\nsec-fetch-site : none\nupgrade-insecure-requests : 1\n}  Converting object to an encodable object failed: Instance of 'Future<List<Hero>>' #0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
#1      _JsonUtf8Stringifier.stringify (dart:convert/json.dart:912:17)
#2      JsonUtf8Encoder.convert (dart:convert/json.dart:374:26)
#3      _FusedConverter.convert (dart:convert/converter.dart:69:48)
#4      Codec.encode (dart:convert/codec.dart:23:32)
#5      Request._responseBodyBytes (package:aqueduct/src/http/request.dart:340:18)
#6      Request.respond (package:aqueduct/src/http/request.dart:251:14)
#7      Controller._sendResponse (package:aqueduct/src/http/controller.dart:327:20)
#8      Controller.receive (package:aqueduct/src/http/controller.dart:164:17)
<asynchronous suspension>
#9      _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:391:17)
#10     Controller.receive (package:aqueduct/src/http/controller.dart:194:28)
<asynchronous suspension>
#11     Router.receive (package:aqueduct/src/http/router.dart:139:18)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#15     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
#16     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
#17     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#22     _StreamController._add (dart:async/stream_controller.dart:655:7)
#23     _StreamController.add (dart:async/stream_controller.dart:597:5)
#24     _HttpServer._handleRequest (dart:_http/http_impl.dart:2837:19)
#25     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2596:19)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#30     _StreamController._add (dart:async/stream_controller.dart:655:7)
#31     _StreamController.add (dart:async/stream_controller.dart:597:5)
#32     _HttpParser._headersEnd (dart:_http/http_parser.dart:399:19)
#33     _HttpParser._doParse (dart:_http/http_parser.dart:739:15)
#34     _HttpParser._parse (dart:_http/http_parser.dart:328:7)
#35     _HttpParser._onData (dart:_http/http_parser.dart:850:5)
#36     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#39     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#40     _StreamController._add (dart:async/stream_controller.dart:655:7)
#41     _StreamController.add (dart:async/stream_controller.dart:597:5)
#42     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1374:10)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#47     _StreamController._add (dart:async/stream_controller.dart:655:7)
#48     _StreamController.add (dart:async/stream_controller.dart:597:5)
#49     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#50     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#51     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#52     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#53     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#54     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by aloenobilis** [comment]
[emacs typo] `
