### ISSUE TITLE
The getter 'location' was called on null.

### ISSUE THREAD

**Issue by shailandraRajput** [stablekernel/aqueduct#911]
Hi,
I got this error when I'm creating an app
`>aqueduct create my_ap
Can't load Kernel binary: Invalid SDK hash.
-- Aqueduct CLI Version: 4.0.0-b1
*** Uncaught error
    NoSuchMethodError: The getter 'location' was called on null.
Receiver: null
Tried calling: location
  **** Stacktrace
  * #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
  * #1      CLIAqueductGlobal.templateDirectory (package:aqueduct/src/cli/commands/create.dart:347:41)
  * #2      CLIAqueductGlobal.getTemplateLocation (package:aqueduct/src/cli/commands/create.dart:351:12)
  * #3      CLITemplateCreator.handle (package:aqueduct/src/cli/commands/create.dart:51:27)
  * #4      CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #5      CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #6      main (file:///C:/Users/shail/AppData/Local/Pub/Cache/hosted/pub.dev%2547/aqueduct-4.0.0-b1/bin/aqueduct.dart:9:27)
  * #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****`

**Comment by mahboobahmed6577** [comment]
same here:

E:\Flutter>aqueduct create sample_server
-- Aqueduct CLI Version: 3.3.0+1
*** Uncaught error
    NoSuchMethodError: The getter 'location' was called on null.
Receiver: null
Tried calling: location
  **** Stacktrace
  * #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
  * #1      CLIAqueductGlobal.templateDirectory (package:aqueduct/src/cli/commands/create.dart:347:41)
  * #2      CLIAqueductGlobal.getTemplateLocation (package:aqueduct/src/cli/commands/create.dart:351:12)
  * #3      CLITemplateCreator.handle (package:aqueduct/src/cli/commands/create.dart:51:27)
  * #4      CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #5      CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #6      main (file:///C:/Users/lenovo/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/aqueduct-3.3.0+1/bin/aqueduct.dart:9:27)
  * #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****

**Comment by nomanmurtaza786** [comment]
Same issue

**Comment by mahboobahmed6577** [comment]
@shailandraRajput  did you find anything ?

**Comment by shailandraRajput** [comment]
Not till now

**Comment by jayjah** [comment]
Please check this Issue [Issue](https://github.com/stablekernel/aqueduct/issues/908); it is kinda related to your problem. Because aqueduct can't find the global installed aqueduct program, which includes the templates. Actually it can't resolve the local path on your computer.

**Comment by nomanmurtaza786** [comment]
> Please check this Issue [Issue](https://github.com/stablekernel/aqueduct/issues/908); it is kinda related to your problem. Because aqueduct can't find the global installed aqueduct program, which includes the templates. Actually it can't resolve the local path on your computer.

Thanks.

**Comment by will-dev8787** [comment]
I'm trying to setup and start a simple Aqueduct project here and am blocked by this same issue here.

Given that - apparently - the problem is identified, are there any plans of setting up the correct environments - or at least including these steps in the official setup of the framework - so we don't have to go scavenging the internet to try and workaround this problem?
