### ISSUE TITLE
Error while following Oauth2 tutorial

### ISSUE THREAD

**Issue by tusharsadhwani** [stablekernel/aqueduct#912]
Following error occurs when running the `/auth/token` endpoint.

I'm using the latest aqueduct 4.0.0-b1 from github, and dart 2.10

```
[SEVERE] aqueduct: POST /auth/token 39ms 500 {user-agent : PostmanRuntime/7.26.5\nconnection : keep-alive\naccept : */*\npostman-token : 4ca8e4e9-462d-429f-a4f2-8db511cbcee3\naccept-encoding : gzip, deflate, br\ncontent-length : 51\nauthorization : Basic Y29tLmhlcm9lcy50dXRvcmlhbDo=\nhost : localhost:8888\ncontent-type : application/x-www-form-urlencoded\n}  NoSuchMethodError: The getter 'dataModel' was called on null.
Receiver: null
Tried calling: dataModel #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new Query (package:aqueduct/src/db/query/query.dart:30:28)
#2      ManagedAuthDelegate.getClient (package:aqueduct/managed_auth.dart:426:19)
#3      AuthServer.getClient (package:aqueduct/src/auth/authorization_server.dart:127:21)
#4      AuthServer.authenticate (package:aqueduct/src/auth/authorization_server.dart:168:26)
#5      AuthController.grant (package:aqueduct/src/auth/auth_controller.dart:79:40)
#6      _InstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:337:37)
#7      _InstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:333:25)
#8      ResourceControllerRuntimeImpl.getOperationForMethod.<anonymous closure> (package:aqueduct/src/runtime/resource_controller_impl.dart:288:16)
#9      ResourceController._process (package:aqueduct/src/http/resource_controller.dart:361:45)
<asynchronous suspension>
#10     ResourceController.handle (package:aqueduct/src/http/resource_controller.dart:142:14)
<asynchronous suspension>
#11     Controller.receive (package:aqueduct/src/http/controller.dart:162:30)
#12     _ControllerRecycler.receive (package:aqueduct/src/http/controller.dart:391:17)
#13     Controller.receive (package:aqueduct/src/http/controller.dart:194:28)
<asynchronous suspension>
#14     Router.receive (package:aqueduct/src/http/router.dart:139:18)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
#19     _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
#21     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#25     _StreamController._add (dart:async/stream_controller.dart:682:7)
#26     _StreamController.add (dart:async/stream_controller.dart:624:5)
#27     _HttpServer._handleRequest (dart:_http/http_impl.dart:2977:19)
#28     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2732:19)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#33     _StreamController._add (dart:async/stream_controller.dart:682:7)
#34     _StreamController.add (dart:async/stream_controller.dart:624:5)
#35     _HttpParser._headersEnd (dart:_http/http_parser.dart:408:17)
#36     _HttpParser._doParse (dart:_http/http_parser.dart:740:15)
#37     _HttpParser._parse (dart:_http/http_parser.dart:324:7)
#38     _HttpParser._onData (dart:_http/http_parser.dart:853:5)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#43     _StreamController._add (dart:async/stream_controller.dart:682:7)
#44     _StreamController.add (dart:async/stream_controller.dart:624:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#46     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#47     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#48     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#49     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#50     _StreamController._add (dart:async/stream_controller.dart:682:7)
#51     _StreamController.add (dart:async/stream_controller.dart:624:5)
#52     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#53     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#55     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#56     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

I also checked my database after running `aqueduct auth add-client --id com.tusharsadhwani.instachat`

```
instachat=# select * from _authclient;
              id              | hashedsecret | salt | redirecturi | allowedscope
------------------------------+--------------+------+-------------+--------------
 com.tusharsadhwani.instachat |              |      |             |
(1 row)
```

**Comment by tusharsadhwani** [comment]
Ok, I fixed it:

```dart
    final authStorage = ManagedAuthDelegate<User>(context);
    authServer = AuthServer(authStorage);

    context = ManagedContext(dataModel, persistentStore);
```

i was creating authStorage before context, so context was null
