### ISSUE TITLE
aqueduct db upgrade gives range error : Invalid value: Not in inclusive range 0..1114111: -1

### ISSUE THREAD

**Issue by 91priyansh** [stablekernel/aqueduct#950]
**** Stacktrace
  * #0      StringBuffer.writeCharCode (dart:core-patch/string_buffer_patch.dart:74:9)
  * #1      PostgreSQLFormat.substitute (package:postgres/src/substituter.dart:83:29) 
  * #2      Query.sendExtended (package:postgres/src/query.dart:61:38)
  * #3      _PostgreSQLConnectionStateIdle.processQuery (package:postgres/src/connection_fsm.dart:182:9)
  * #4      _PostgreSQLConnectionStateIdle.awake (package:postgres/src/connection_fsm.dart:168:14)
  * #5      _PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:399:67)
  * #6      _PostgreSQLExecutionContextMixin.query (package:postgres/src/connection.dart:318:12)
  * #7      PostgreSQLPersistentStore.execute (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:153:37)
  * <asynchronous suspension>
  * #8      PostgreSQLPersistentStore.schemaVersion (package:aqueduct/src/db/postgresql/postgresql_persistent_store.dart:216:26)
  * #9      CLIDatabaseUpgrade.handle (package:aqueduct/src/cli/commands/db_upgrade.dart:28:52)
  * #10     CLICommand.process (package:aqueduct/src/cli/command.dart:159:20)
  * <asynchronous suspension>
  * #11     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #12     CLICommand.process (package:aqueduct/src/cli/command.dart:135:12)
  * #13     main (file:///C:/Users/DELL/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/aqueduct-3.3.0+1/bin/aqueduct.dart:9:27)
  * #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
  * #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
  ****
Dart version is 2.10.5 (stable)

**Comment by maulaniad** [comment]
https://github.com/stablekernel/aqueduct/issues/844#issuecomment-733024542 

this worked for me

**Comment by ali-thowfeek** [comment]
> [#844 (comment)](https://github.com/stablekernel/aqueduct/issues/844#issuecomment-733024542)
> 
> this worked for me

That is:
`dart pub run aqueduct db upgrade`

For some reason i cant generate more than one migration file, so i had to delete the old one and generate new migration file each time. Also had to reset the whole database before running the upgrade command. I hope this benefits you.
